[package]
name = "test-rust-chan-chan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
crossbeam-channel = "0.5.6"
rand = "0.8.5"
